// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "ap-southeast-2",
    "aws_cognito_identity_pool_id": "ap-southeast-2:b64d3261-eb8f-4a60-a8e1-a24ba20c88d6",
    "aws_cognito_region": "ap-southeast-2",
    "aws_user_pools_id": "ap-southeast-2_gEjADJYEL",
    "aws_user_pools_web_client_id": "1253mmovemk6l58nscaf3e9cud"
};


export default awsmobile;
